/* Generated by Software/protocol.py - do not edit by hand. */
#ifndef FMMA_PROTOCOL_H
#define FMMA_PROTOCOL_H

/* Word indices into the shared on-chip RAM. The HPS maps the RAM at
 * the lightweight HPS-to-FPGA bridge base and indexes it as a
 * volatile unsigned int array, so word N is at byte offset 4*N. */

#define FMMA_PROTOCOL_VERSION        2u  /* protocol version implemented here */
#define FMMA_MEM_WORDS               1024u  /* size of the shared RAM in 32-bit words */
#define FMMA_PROGRAM_BASE            8u  /* word address the CPU program loads at */
#define FMMA_PROGRAM_LIMIT           256u  /* first word after the program area */
#define FMMA_INPUT_BASE              256u  /* first HPS -> FPGA word */
#define FMMA_OUTPUT_BASE             320u  /* first FPGA -> HPS word */
#define FMMA_PRICE_SCALE             100u  /* fixed-point scale for prices and sizes */
#define FMMA_SIGNAL_NONE             0u
#define FMMA_SIGNAL_BUY              1u
#define FMMA_SIGNAL_SELL             2u
#define FMMA_FILL_BOUGHT             1u
#define FMMA_FILL_SOLD               2u
#define FMMA_STATUS_RUNNING          1u
#define FMMA_STATUS_DATA_VALID       2u
#define FMMA_STATUS_RISK_BLOCKED     4u
#define FMMA_STATUS_DISABLED         8u

/* HPS -> FPGA */
#define FMMA_TICK_SEQ                256u
#define FMMA_BID                     257u
#define FMMA_ASK                     258u
#define FMMA_BID_SIZE                259u
#define FMMA_ASK_SIZE                260u
#define FMMA_CFG_THRESH              261u
#define FMMA_CFG_MAX_POS             262u
#define FMMA_CFG_ENABLE              263u
#define FMMA_CFG_HALF_SPREAD         264u
#define FMMA_CFG_SKEW                265u
#define FMMA_CFG_RESTART             266u
#define FMMA_FILL_SEQ                267u
#define FMMA_FILL_SIDE               268u
#define FMMA_FILL_QTY                269u
#define FMMA_CFG_POSITION            270u

/* FPGA -> HPS */
#define FMMA_HEARTBEAT               320u
#define FMMA_SIGNAL                  321u
#define FMMA_SIGNAL_TICK             322u
#define FMMA_SIGNAL_SEQ              323u
#define FMMA_POSITION                324u
#define FMMA_STATUS                  325u
#define FMMA_REJECTS                 326u
#define FMMA_FW_VERSION              327u
#define FMMA_QUOTE_BID               328u
#define FMMA_QUOTE_ASK               329u

#endif /* FMMA_PROTOCOL_H */
