// Auto-generated by Assembler.py from trading.asm. Do not edit.
#ifndef FPGA_PROGRAM_H
#define FPGA_PROGRAM_H

#define FPGA_PROGRAM_BASE 8u
#define FPGA_PROGRAM_LEN  45u

static const unsigned int fpga_program[FPGA_PROGRAM_LEN] = {
    0x00000131u,   // word 8
    0x00002140u,   // word 9
    0x00000232u,   // word 10
    0x00002241u,   // word 11
    0x00000333u,   // word 12
    0x00002342u,   // word 13
    0x00000737u,   // word 14
    0x00002701u,   // word 15
    0x00000838u,   // word 16
    0x018628A0u,   // word 17
    0x00000C3Cu,   // word 18
    0x00002C43u,   // word 19
    0x00000D3Du,   // word 20
    0x00002F16u,   // word 21
    0x00004401u,   // word 22
    0x00004502u,   // word 23
    0x00000D57u,   // word 24
    0x00004D4Cu,   // word 25
    0x000004B0u,   // word 26
    0x0000C0FBu,   // word 27
    0x000005B0u,   // word 28
    0x0000C0F9u,   // word 29
    0x000004B5u,   // word 30
    0x0000C60Eu,   // word 31
    0x000009B0u,   // word 32
    0x0000C009u,   // word 33
    0x00000BF9u,   // word 34
    0x00000B98u,   // word 35
    0x000004BBu,   // word 36
    0x0000C608u,   // word 37
    0x00000BFAu,   // word 38
    0x00000B58u,   // word 39
    0x00000BB5u,   // word 40
    0x0000C608u,   // word 41
    0x000009F4u,   // word 42
    0x00000AF5u,   // word 43
    0x00004ECFu,   // word 44
    0x00000636u,   // word 45
    0x00002601u,   // word 46
    0x00004643u,   // word 47
    0x0000CEFAu,   // word 48
    0x00000636u,   // word 49
    0x00002602u,   // word 50
    0x00004643u,   // word 51
    0x0000CEF6u   // word 52
};

#endif
