#!/usr/bin/env python3
"""Generate ALU test vectors from the golden model for the RTL testbench.

``Testbenches/tb_alu.v`` reads the file this produces, drives ``Code/ALUFinal``
with every case and fails if the hardware and ``fmma_sim.alu`` disagree about
either the result or the flags.  That turns "the simulator models the ALU" from
a claim in a docstring into something the regression suite proves.

The cases are directed edge cases plus a deterministic pseudo-random sweep, so
the file is reproducible: regenerating it on any machine gives byte-identical
output.

    python gen_alu_vectors.py            # -> ../Testbenches/alu_vectors.txt
    python gen_alu_vectors.py --count 64 # smaller random sweep per opcode

Line format (all hex, one case per line):
    <opcode> <A> <B> <cin> <expected_C> <expected_flags>
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

import fmma_isa as isa
import fmma_sim as sim

#: Values chosen to hit sign boundaries, carry/overflow edges and the shift
#: amounts where the old implementation went wrong.
EDGE_VALUES = [
    0x00000000, 0x00000001, 0x00000002, 0x0000000F, 0x000000FF,
    0x00007FFF, 0x00008000, 0x0000FFFF, 0x00010000,
    0x7FFFFFFE, 0x7FFFFFFF, 0x80000000, 0x80000001,
    0xFFFFFFFE, 0xFFFFFFFF, 0xF0F0F0F0, 0x0F0F0F0F,
    0x3B9ACA00,          # 1e9, a realistic scaled price
    0x05F5E100,          # 1e8
]

#: Every 5-bit shift amount matters for LSH/ASH, since the amount is signed.
SHIFT_VALUES = list(range(32))


def cases(count, seed=20260911):
    rng = random.Random(seed)
    for mnemonic, opcode in sorted(isa.ALU_OPCODES.items(), key=lambda kv: kv[1]):
        seen = set()

        def emit(a, b, cin):
            key = (a, b, cin)
            if key in seen:
                return None
            seen.add(key)
            return (mnemonic, opcode, a, b, cin)

        # Directed: every edge value against every edge value is too many, so
        # pair each edge value with a handful of others plus itself.
        for a in EDGE_VALUES:
            for b in EDGE_VALUES:
                c = emit(a, b, 0)
                if c:
                    yield c
            c = emit(a, a, 1)
            if c:
                yield c

        if mnemonic in ("LSH", "ASH"):
            for a in EDGE_VALUES:
                for sh in SHIFT_VALUES:
                    c = emit(a, sh, 0)
                    if c:
                        yield c

        if mnemonic in ("ADDC", "SUBC"):
            for a in EDGE_VALUES:
                for b in EDGE_VALUES[:6]:
                    c = emit(a, b, 1)
                    if c:
                        yield c

        for _ in range(count):
            c = emit(rng.getrandbits(32), rng.getrandbits(32), rng.getrandbits(1))
            if c:
                yield c


def main(argv=None):
    p = argparse.ArgumentParser(description="generate ALU vectors")
    p.add_argument("--count", type=int, default=256,
                   help="random cases per opcode (default 256)")
    p.add_argument("-o", "--output",
                   default=str(Path(__file__).resolve().parent.parent
                              / "Testbenches" / "alu_vectors.txt"))
    args = p.parse_args(argv)

    lines = []
    n = 0
    for mnemonic, opcode, a, b, cin in cases(args.count):
        result, flags = sim.alu(mnemonic, a, b, cin)
        lines.append(f"{opcode:x} {a:08x} {b:08x} {cin:x} "
                     f"{result:08x} {flags.as_int():02x}")
        n += 1

    header = [
        "// Generated by Software/gen_alu_vectors.py - do not edit by hand.",
        "// opcode A B cin expected_C expected_flags   (all hex)",
        "// flags = {Z, C, F, L, N} in bits 4..0",
        f"// {n} cases",
    ]
    Path(args.output).write_text("\n".join(header + lines) + "\n",
                                 encoding="ascii", newline="\n")
    print(f"wrote {n} vectors to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
